sitename:
  image: claudiucreanga/magento2
  domainname: sitename.docker
  hostname: sitename
  ports:
    - "882:80"
  environment:
    - SAMBA_START=1
  volumes:
    - ~/.composer:/home/magento/.composer
    - ./composer.json:/magento2/composer.json
    - ./composer.lock:/magento2/composer.lock
    - ./app/:/magento2/app/
    - ./dev/:/magento2/dev/
    - ./lib/:/magento2/lib/
    - ./setup/:/magento2/setup/
