sitename:
  image: claudiucreanga/magento2-docker
  domainname: sitename.docker
  hostname: sitename
  ports:
    - "80:80"
    - "3000:3000"
    - "9000:9000"
  environment:
    - SAMBA_START=0
  volumes:
    - ~/.composer:/home/magento/.composer
    - ./composer.json:/magento2/composer.json
    - ./composer.lock:/magento2/composer.lock
    - ./app/:/magento2/app/
    - ./dev/:/magento2/dev/
    - ./lib/:/magento2/lib/
    - ./setup/:/magento2/setup/
