#!/bin/sh

# Install xdebug, but leave it disabled

touch /usr/local/etc/php/conf.d/xdebug.ini
echo "xdebug.remote_enable=0" >> /usr/local/etc/php/conf.d/xdebug.ini
echo "xdebug.profiler_enable=0" >> /usr/local/etc/php/conf.d/xdebug.ini
echo "xdebug.remote_autostart=0" >> /usr/local/etc/php/conf.d/xdebug.ini 
echo "xdebug.remote_connect_back=0" >> /usr/local/etc/php/conf.d/xdebug.ini 
echo "xdebug.remote_port=9000" >> /usr/local/etc/php/conf.d/xdebug.ini 
echo "xdebug.remote_log=/tmp/php5-xdebug.log" >> /usr/local/etc/php/conf.d/xdebug.ini
mkdir ~/software && \
cd  ~/software/ && \
apt-get install -y wget && \
wget http://xdebug.org/files/xdebug-2.4.1.tgz && \
tar -xvzf xdebug-2.4.1.tgz && \
cd xdebug-2.4.1 && \
phpize && \
./configure && \
make && \
cp modules/xdebug.so /usr/local/lib/php/extensions/no-debug-non-zts-20151012 && \
echo ";zend_extension = /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so" >>  /usr/local/etc/php/php.ini
